### ISSUE TITLE
Recycle / reimplement Rockwell features from Pug to React

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#92]
- [x] Render regular tweets [reimplement in React]
- [x] Render retweets [reimplement in React]
- [x] Render quotes (aka quoted retweets) with indentation (see #46) and make sure embedded cards are shown, but not rendered images [reimplement in React] @RobertAndion 
- [x] #100  @RobertAndion 
- [x] Engagements (like, retweet, click on article) [reimplement in React]
- [x] #98
- [x] Adjust aspect ratio of images based on screen width
- [x] Adjust feed width on devices with large screen (make sure margins are OK etc) @RobertAndion 
- [x] Attention check [reimplement in React] @saumyabhadani95 and @RobertAndion 
- [x] Next button and pagination (feed, followed by attention check, etc.) [reimplement in React] @saumyabhadani95 
- [x] #73  [reimplement/port from HTML+CSS in React] @thomasbiv 
- [x] ~~Pre-treatment attention check [reimplement in React]~~
- [x] #88 @thomasbiv with @RobertAndion to give any help.
